/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaGrafica;

import javax.swing.ImageIcon;

/**
 *
 * @author wrydmoon
 */
public class MenuGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MenuGeneral
     */
    
    private final CargoGUI cargoGUI;
    private final PaisGUI paisGUI;
    private final DepartamentoGUI departamentoGUI;
    private final MunicipioGUI municipioGUI;
    private final DireccionGUI direccionGUI;
    private final PersonaGUI personaGUI;
    private final EmpleadoGUI empleadoGUI;
    private final EstudianteGUI estudianteGUI;
            
    
    public MenuGeneral() {
        
        initComponents();       
        this.cargoGUI = new CargoGUI();
        this.paisGUI = new PaisGUI();
        this.departamentoGUI = new DepartamentoGUI();
        this.municipioGUI = new MunicipioGUI();
        this.direccionGUI = new DireccionGUI();
        this.personaGUI = new PersonaGUI();
        this.empleadoGUI = new EmpleadoGUI();
        this.estudianteGUI = new EstudianteGUI();
        
  
        CargoBtn.setIcon(new ImageIcon("Iconos/cargo.png"));
        DepartamentoBtn.setIcon(new ImageIcon("Iconos/departamento.png"));
        DireccionBtn.setIcon(new ImageIcon("Iconos/direccion.png"));
        EmpleadoBtn.setIcon(new ImageIcon("Iconos/empleado.png"));
        EstudianteBtn.setIcon(new ImageIcon("Iconos/estudiante.png"));
        MunicipioBtn.setIcon(new ImageIcon("Iconos/municipio.png"));
        PaisBtn.setIcon(new ImageIcon("Iconos/pais.png"));
        PersonaBtn.setIcon(new ImageIcon("Iconos/persona.png"));
        
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        CargoBtn = new javax.swing.JButton();
        PaisBtn = new javax.swing.JButton();
        DepartamentoBtn = new javax.swing.JButton();
        MunicipioBtn = new javax.swing.JButton();
        DireccionBtn = new javax.swing.JButton();
        PersonaBtn = new javax.swing.JButton();
        EmpleadoBtn = new javax.swing.JButton();
        EstudianteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));
        setResizable(false);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("CRUD DE ENTIDADES");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CargoBtn.setText("Cargo");
        CargoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoBtnActionPerformed(evt);
            }
        });

        PaisBtn.setText("Pais");
        PaisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisBtnActionPerformed(evt);
            }
        });

        DepartamentoBtn.setText("Departamento");
        DepartamentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoBtnActionPerformed(evt);
            }
        });

        MunicipioBtn.setText("Municipio");
        MunicipioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioBtnActionPerformed(evt);
            }
        });

        DireccionBtn.setText("Direccion");
        DireccionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionBtnActionPerformed(evt);
            }
        });

        PersonaBtn.setText("Persona");
        PersonaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaBtnActionPerformed(evt);
            }
        });

        EmpleadoBtn.setText("Empleado");
        EmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoBtnActionPerformed(evt);
            }
        });

        EstudianteBtn.setText("Estudiante");
        EstudianteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DireccionBtn)
                    .addComponent(CargoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PaisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PersonaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartamentoBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(EmpleadoBtn)))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MunicipioBtn)
                    .addComponent(EstudianteBtn))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartamentoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MunicipioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstudianteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DireccionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PersonaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmpleadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoBtnActionPerformed
        cargoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CargoBtnActionPerformed

    private void EmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoBtnActionPerformed
        empleadoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmpleadoBtnActionPerformed

    private void PaisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisBtnActionPerformed
        paisGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PaisBtnActionPerformed

    private void DepartamentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoBtnActionPerformed
        departamentoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DepartamentoBtnActionPerformed

    private void MunicipioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioBtnActionPerformed
        municipioGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MunicipioBtnActionPerformed

    private void DireccionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionBtnActionPerformed
        direccionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DireccionBtnActionPerformed

    private void PersonaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaBtnActionPerformed
        personaGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PersonaBtnActionPerformed

    private void EstudianteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteBtnActionPerformed
        estudianteGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EstudianteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargoBtn;
    private javax.swing.JButton DepartamentoBtn;
    private javax.swing.JButton DireccionBtn;
    private javax.swing.JButton EmpleadoBtn;
    private javax.swing.JButton EstudianteBtn;
    private javax.swing.JButton MunicipioBtn;
    private javax.swing.JButton PaisBtn;
    private javax.swing.JButton PersonaBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTitulo;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
